package api.employeeService.enums;

public enum Department {
    BUSINESS_DEVELOPMENT,
    BUSINESS_INFORMATION_SYSTEM,
    CORPORATE_PLANNING,
    CORPORATE_AFFAIRS,
    MARKETING,
    CORPORATE_COMMUNICATION,
    CORPORATE_SOCIAL_RESPONSIBILITY,
    CONTRACT_AND_PROCUREMENT,
    CIVIL,
    EXPLORATION_AND_PRODUCTION,
    FINANCE,
    HUMAN_RESOURCE,
    LEGAL,
    OPERATIONS_AND_MAINTENANCE,
    PETROCHEMICAL,
    PROJECTS,
    PRICING,
    RESEARCH_AND_DEVELOPMENT,
    SECURITY
}
