name: mobile_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  get: ^4.6.6
  http: ^1.2.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  lottie: ^3.1.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/animations/
